# Generated by Django 4.2.7 on 2024-03-02 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('slug', models.SlugField(max_length=40)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cloth/images')),
            ],
        ),
        migrations.CreateModel(
            name='Cloth',
            fields=[
                ('clothid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('description', models.TextField()),
                ('rating', models.FloatField(default=0.0)),
                ('image', models.ImageField(upload_to='cloth/images')),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('slug', models.SlugField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('slug', models.SlugField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('rating', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=10)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('cloth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='cloth.cloth')),
            ],
        ),
        migrations.CreateModel(
            name='ClothWishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clothid', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('description', models.TextField()),
                ('rating', models.FloatField(default=0.0)),
                ('image', models.ImageField(upload_to='cloth/images')),
                ('Size', models.ManyToManyField(to='cloth.size')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloth.category')),
                ('color', models.ManyToManyField(to='cloth.color')),
            ],
        ),
        migrations.CreateModel(
            name='ClothCartList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clothid', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('description', models.TextField()),
                ('rating', models.FloatField(default=0.0)),
                ('image', models.ImageField(upload_to='cloth/images')),
                ('Size', models.ManyToManyField(to='cloth.size')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloth.category')),
                ('color', models.ManyToManyField(to='cloth.color')),
            ],
        ),
        migrations.AddField(
            model_name='cloth',
            name='Size',
            field=models.ManyToManyField(to='cloth.size'),
        ),
        migrations.AddField(
            model_name='cloth',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cloth',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloth.category'),
        ),
        migrations.AddField(
            model_name='cloth',
            name='color',
            field=models.ManyToManyField(to='cloth.color'),
        ),
    ]
