# Generated by Django 4.2.7 on 2024-05-20 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloth', '0002_alter_category_image_alter_cloth_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='image',
            field=models.URLField(),
        ),
    ]
