# Generated by Django 4.2.7 on 2024-05-20 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloth', '0005_alter_clothwishlist_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothcartlist',
            name='image',
            field=models.URLField(),
        ),
    ]
