# Generated by Django 4.2.7 on 2024-05-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloth', '0006_alter_clothcartlist_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloth',
            name='image2',
            field=models.URLField(blank=True, null=True),
        ),
    ]
