# Generated by Django 4.2.7 on 2024-03-12 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UpdateProfile',
        ),
    ]
