# Generated by Django 4.2.7 on 2024-03-22 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='cloth/profile_images'),
        ),
    ]
